[package]
name = "tamda"
version = "0.1.0"
edition = "2024"

[dependencies]
marcli = "0.2.0"
clap = { version = "4.6.1", features = ["derive"] }
clap_complete = "4.6.5"
reqwest = {
    version = "0.13",
    default-features = false,
    features = ["native-tls", "blocking"]
}
anyhow = "1.0.103"
minus = { version = "5.7.1", features = ["static_output", "search"] }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
